### ISSUE TITLE
Error: No URL provided.

### ISSUE THREAD

**Issue by VenuNarukulla** [twitf/yii2-dropzone#1]
This extension  looks great, 
Why i am getting the below error?
```Error: No URL provided.
dropzone.js:1060:13
Error: Dropzone already attached.
dropzone.js:1034:13
```

**Comment by VenuNarukulla** [comment]
solved by removing `'class' => 'dropzone' `

**Comment by twitf** [comment]
这个我测试 是没有问题的（有必要你需要贴上你的代码）  你可以参考
`http://www.dropzonejs.com/#configuration-options`这里来配置参数
