### ISSUE TITLE
TypeError: file.previewElement.getElementsByTagName(...)[0] is undefined

### ISSUE THREAD

**Issue by VenuNarukulla** [twitf/yii2-dropzone#2]
Hi,

Can anyone put a light on the above error? that is in the console when I click on 'Remove'

**Comment by twitf** [comment]
Sorry, I can't judge your problems from your issues. I guess you should not add the delete operation.
    public function actions()
    {
        return [
            'upload' => [
                'class' => 'twitf\dropzone\UploadAction',
                'config' => [
                    "filePathFormat" => "/uploads/image/".date('YmdHis').'/', //上传保存路径
                    "fileRoot" => Yii::getAlias("@webroot"),//上传根目录
                ],
            ],
            'remove' => [
                'class' => 'twitf\dropzone\RemoveAction',
                'config' => [
                    "fileRoot" => Yii::getAlias("@webroot"),//上传根目录
                ],
            ],

        ];
    }

**Comment by twitf** [comment]
Sorry, can you describe this problem in detail? The test is no problem. What is your version of Jquery?> > 
> Controller

```php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;

class IndexController extends Controller
{
    public function actions()
    {
        return [
            'upload' => [
                'class' => 'twitf\dropzone\UploadAction',
                'config' => [
                    "filePathFormat" => "/uploads/image/".date('YmdHis').'/', 
                    "fileRoot" => Yii::getAlias("@webroot"),
                ],
            ],
            'remove' => [
                'class' => 'twitf\dropzone\RemoveAction',
                'config' => [
                    "fileRoot" => Yii::getAlias("@webroot"),
                ],
            ],

        ];
    }
}
```

> View

```php
<?php
echo \twitf\dropzone\DropZone::widget();
?>
```

**Comment by VenuNarukulla** [comment]
Thank you for your reply,
I just understood the issue, the error is showing up when I try to delete a file which doesn't uploaded successfully.
I will close this issue.

But the `Remove` or `Cancel` links are showing only if I add`mockfiles`.
If I don't add `mockfiles` , the `Remove` link is not showing up

**Comment by twitf** [comment]
If the conditions permit, can provide detailed code? Allows me to better understand your problems.
